attributes_train_5.csv:
  MetroSummer:
    - MetroStage_1:
        - att_3
        - att_4
    - MetroStage_2:
        - att_3
        - att_4
    - MetroStage_3:
        - att_3
        - att_4
    - MetroStage_4:
        - att_3
        - att_4
    - MetroStage_5:
        - att_3
        - att_4
  PandaImgs:
    - PandaStage_2:
        - att_3
        - att_4
    - PandaStage_3:
        - att_3
        - att_4
    - PandaStage_4:
        - att_3
        - att_4
  Ivideon_v4:
    - train_imgs:
        - att_3
        - att_4
  CrowdHuman_v1:
    - train:
        - att_3
        - att_4
  MetroSummer_train:
    - att_3
    - att_4